sonar.projectKey=crapougnax_modaka
sonar.organization=crapougnax

sonar.sources=src
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
